table 'Traineess'' Satisfaction_KOBO (4)'
	lineageTag: 8b0fbda8-17ac-4ff3-9ff7-2ef8be719842

	column intro_text
		dataType: string
		lineageTag: 04522024-a3a9-4086-8b44-312cd84ddbfb
		summarizeBy: none
		sourceColumn: intro_text

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: string
		lineageTag: 714a49f9-6955-4bb4-a073-ea4d36e0fd4e
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: string
		lineageTag: 5cb44f92-b09b-454e-8685-f1729ffccf1c
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

	column org
		dataType: string
		lineageTag: c349ea4a-ba83-4b8a-b208-dbf12434346e
		summarizeBy: none
		sourceColumn: org

		annotation SummarizationSetBy = Automatic

	column If_other_specify
		dataType: string
		lineageTag: 61a36acc-a558-4c15-825e-75fdfba1b0ba
		summarizeBy: none
		sourceColumn: If_other_specify

		annotation SummarizationSetBy = Automatic

	column fund
		dataType: string
		lineageTag: e5297031-2a2f-48d8-a4d4-465506f46b6a
		summarizeBy: none
		sourceColumn: fund

		annotation SummarizationSetBy = Automatic

	column contract_No
		dataType: string
		lineageTag: c0d674a9-79e8-427f-bf61-ee20b3da7de2
		summarizeBy: none
		sourceColumn: contract_No

		annotation SummarizationSetBy = Automatic

	column feedback_date
		dataType: string
		lineageTag: e4b3aaab-e382-45e8-8f4a-421138a284e7
		summarizeBy: none
		sourceColumn: feedback_date

		annotation SummarizationSetBy = Automatic

	column provider
		dataType: string
		lineageTag: 92ed0bb7-12aa-44fd-9b3d-6a02affdaa13
		summarizeBy: none
		sourceColumn: provider

		annotation SummarizationSetBy = Automatic

	column other_tp_name
		dataType: string
		lineageTag: 0e013379-2344-4985-98db-ddf31a261141
		summarizeBy: none
		sourceColumn: other_tp_name

		annotation SummarizationSetBy = Automatic

	column course
		dataType: string
		lineageTag: 59ea1e82-d7a1-46da-b996-935947e18ac3
		summarizeBy: none
		sourceColumn: course

		annotation SummarizationSetBy = Automatic

	column Choose_Type_of_Training
		dataType: string
		lineageTag: 74bd3f9d-adbf-4a9b-95fc-62644fd2cfe6
		summarizeBy: none
		sourceColumn: Choose_Type_of_Training

		annotation SummarizationSetBy = Automatic

	column Trainee_Name
		dataType: string
		lineageTag: c6a9f58d-3809-4e3e-bcfc-efe4a54201d0
		summarizeBy: none
		sourceColumn: Trainee_Name

		annotation SummarizationSetBy = Automatic

	column sex
		dataType: string
		lineageTag: 9d646295-e32a-42dd-8acf-fed3effbffe3
		summarizeBy: none
		sourceColumn: sex

		annotation SummarizationSetBy = Automatic

	column program_type
		dataType: string
		lineageTag: 20f37031-618f-4a79-b0c1-798cc18bef56
		summarizeBy: none
		sourceColumn: program_type

		annotation SummarizationSetBy = Automatic

	column batch_number
		dataType: string
		lineageTag: 91deb988-36bc-46ca-b98c-7d901aa6977e
		summarizeBy: none
		sourceColumn: batch_number

		annotation SummarizationSetBy = Automatic

	column rating_note
		dataType: string
		lineageTag: a7404e68-8736-4840-9d38-19c7f32850bc
		summarizeBy: none
		sourceColumn: rating_note

		annotation SummarizationSetBy = Automatic

	column q1_1
		dataType: double
		lineageTag: 56b1ef1e-8c66-4438-b7f6-9f92f2ffd2be
		summarizeBy: sum
		sourceColumn: q1_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_1_explain
		dataType: string
		lineageTag: 2ea0316c-3ffb-40ea-9102-f179effaacd5
		summarizeBy: none
		sourceColumn: q1_1_explain

		annotation SummarizationSetBy = Automatic

	column q1_2
		dataType: double
		lineageTag: 12d51c3c-fb98-4119-ae45-c330cbf36152
		summarizeBy: sum
		sourceColumn: q1_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_2_explain
		dataType: string
		lineageTag: a9eaae40-ff8d-4d74-bbf5-f328330f624f
		summarizeBy: none
		sourceColumn: q1_2_explain

		annotation SummarizationSetBy = Automatic

	column q1_3
		dataType: double
		lineageTag: 0327fe72-2f5c-4e26-b71b-4dca1b6e725d
		summarizeBy: sum
		sourceColumn: q1_3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_3_explain
		dataType: string
		lineageTag: 591de2c3-2025-4a3b-83d0-c7436ea78fca
		summarizeBy: none
		sourceColumn: q1_3_explain

		annotation SummarizationSetBy = Automatic

	column q1_4
		dataType: double
		lineageTag: af6a4660-5968-44ad-b031-9cc3dbec3d42
		summarizeBy: sum
		sourceColumn: q1_4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_4_explain
		dataType: string
		lineageTag: 436f9159-f74a-46b9-ad6f-81ec6c3c3373
		summarizeBy: none
		sourceColumn: q1_4_explain

		annotation SummarizationSetBy = Automatic

	column q1_5
		dataType: double
		lineageTag: 576ebf73-933c-47e8-bb38-ff76fd2f682f
		summarizeBy: sum
		sourceColumn: q1_5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_5_explain
		dataType: string
		lineageTag: dc11b894-1ca6-45a3-9240-c7bca1166e4c
		summarizeBy: none
		sourceColumn: q1_5_explain

		annotation SummarizationSetBy = Automatic

	column q1_6
		dataType: double
		lineageTag: 7d264035-0ef5-496c-9dbe-08f4fd3abe43
		summarizeBy: sum
		sourceColumn: q1_6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_6_explain
		dataType: string
		lineageTag: 52d8be2a-8b29-4910-9fad-892a410602b6
		summarizeBy: none
		sourceColumn: q1_6_explain

		annotation SummarizationSetBy = Automatic

	column q1_7
		dataType: double
		lineageTag: 96c33e42-892d-447e-b294-c57f0ac23cff
		summarizeBy: sum
		sourceColumn: q1_7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_7_explain
		dataType: string
		lineageTag: d6814e68-376a-43c7-990d-eaa0dac9c545
		summarizeBy: none
		sourceColumn: q1_7_explain

		annotation SummarizationSetBy = Automatic

	column q1_8
		dataType: double
		lineageTag: 0ce1bea9-f3f4-45b8-aa31-7b2dfd39f325
		summarizeBy: sum
		sourceColumn: q1_8

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_8_explain
		dataType: string
		lineageTag: d633fe3d-4b08-4de1-9a0c-acc1875c5573
		summarizeBy: none
		sourceColumn: q1_8_explain

		annotation SummarizationSetBy = Automatic

	column q1_9
		dataType: double
		lineageTag: 5eb16d5c-a544-409e-9c75-a4dd0e89da38
		summarizeBy: sum
		sourceColumn: q1_9

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_9_explain
		dataType: string
		lineageTag: a7cff6e2-0fc3-4836-b9b8-6ad4825a4774
		summarizeBy: none
		sourceColumn: q1_9_explain

		annotation SummarizationSetBy = Automatic

	column overall_score
		dataType: double
		lineageTag: 6e800cf2-580c-4fae-b205-617a8152721d
		summarizeBy: sum
		sourceColumn: overall_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column overall_score_decimal
		dataType: double
		lineageTag: ab266e24-62d5-46a3-86ec-177f414c3ba5
		summarizeBy: sum
		sourceColumn: overall_score_decimal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column overall_display
		dataType: string
		lineageTag: 453691a7-1fbb-434d-8170-dba1c67a4fd4
		summarizeBy: none
		sourceColumn: overall_display

		annotation SummarizationSetBy = Automatic

	column q2_1
		dataType: string
		lineageTag: f0a2442d-1e92-4fae-9f82-60157389b4b3
		summarizeBy: none
		sourceColumn: q2_1

		annotation SummarizationSetBy = Automatic

	column q2_1_specify
		dataType: string
		lineageTag: deaad537-3a79-4b30-a997-20ec258d4018
		summarizeBy: none
		sourceColumn: q2_1_specify

		annotation SummarizationSetBy = Automatic

	column q2_2
		dataType: string
		lineageTag: 79e28e1a-424e-4e0a-8296-4e4a2011ce8c
		summarizeBy: none
		sourceColumn: q2_2

		annotation SummarizationSetBy = Automatic

	column thank_you
		dataType: string
		lineageTag: a542905c-bded-4d24-98dd-33e9254d6c03
		summarizeBy: none
		sourceColumn: thank_you

		annotation SummarizationSetBy = Automatic

	column start
		dataType: string
		lineageTag: 617b38b5-a3d4-4b02-bd18-92a8b4105b24
		summarizeBy: none
		sourceColumn: start

		annotation SummarizationSetBy = Automatic

	column today
		dataType: string
		lineageTag: 9fccaa13-3e8d-4bcc-a037-74fe99472b1a
		summarizeBy: none
		sourceColumn: today

		annotation SummarizationSetBy = Automatic

	column deviceid
		dataType: string
		lineageTag: 7e89ed4c-ad84-4f8d-a09e-4193024be01c
		summarizeBy: none
		sourceColumn: deviceid

		annotation SummarizationSetBy = Automatic

	column _id
		dataType: string
		lineageTag: 4693eb3a-0a97-496e-965d-62d0808f234a
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column _uuid
		dataType: string
		lineageTag: 8cad3a48-e584-496c-981b-895e8fadc8d4
		summarizeBy: none
		sourceColumn: _uuid

		annotation SummarizationSetBy = Automatic

	column _submission_time
		dataType: string
		lineageTag: d42b8758-7f79-4f95-b4ec-c6359760cd9d
		summarizeBy: none
		sourceColumn: _submission_time

		annotation SummarizationSetBy = Automatic

	column _validation_status
		dataType: string
		lineageTag: df330e60-c9a8-4805-8c26-73edad90ec25
		summarizeBy: none
		sourceColumn: _validation_status

		annotation SummarizationSetBy = Automatic

	column _notes
		dataType: string
		lineageTag: d6af53a5-734e-4b06-baa9-cb6baa7efcc9
		summarizeBy: none
		sourceColumn: _notes

		annotation SummarizationSetBy = Automatic

	column _status
		dataType: string
		lineageTag: c7f93467-c8b1-45c1-b3a1-f1fc2b0b4567
		summarizeBy: none
		sourceColumn: _status

		annotation SummarizationSetBy = Automatic

	column _submitted_by
		dataType: string
		lineageTag: e0da7483-3283-44c8-841d-1b7ff14cea08
		summarizeBy: none
		sourceColumn: _submitted_by

		annotation SummarizationSetBy = Automatic

	column __version__
		dataType: string
		lineageTag: f612333a-9dc8-4812-b803-0a9ffb798f40
		summarizeBy: none
		sourceColumn: __version__

		annotation SummarizationSetBy = Automatic

	column _tags
		dataType: string
		lineageTag: fb5cf05e-fd9d-4725-a542-ea6d64e5d30a
		summarizeBy: none
		sourceColumn: _tags

		annotation SummarizationSetBy = Automatic

	column meta/rootUuid
		dataType: string
		lineageTag: 7090ac91-a219-430c-bdd4-3b8dcd4ea759
		summarizeBy: none
		sourceColumn: meta/rootUuid

		annotation SummarizationSetBy = Automatic

	column _index
		dataType: string
		lineageTag: 6c207140-2b32-4603-8e32-c2bdc295136b
		summarizeBy: none
		sourceColumn: _index

		annotation SummarizationSetBy = Automatic

	partition 'Traineess'' Satisfaction_KOBO (4)' = m
		mode: import
		queryGroup: 'Trainees'' Satisfaction_KOBO'
		source =
				let
				    Source = Csv.Document(Web.Contents("https://kf.kobotoolbox.org/api/v2/assets/azRmjXmFEJ2QoFnFcEHMML/export-settings/esWg6hvft4DeMa2vHDvZxqG/data.csv"),[Delimiter=";", Columns=56, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"q1_1", type number}, {"q1_2", type number}, {"q1_3", type number}, {"q1_4", type number}, {"q1_5", type number}, {"q1_6", type number}, {"q1_7", type number}, {"q1_8", type number}, {"q1_9", type number}, {"overall_score", type number}, {"overall_score_decimal", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

